### PR TITLE
2.8 fixes

### PR DESCRIPTION
**Pull request by hsab**
Minor fixes to make compatible with 2.8
Mainly change version number
Fix the to_mesh call based on [new api](https://docs.blender.org/api/master/bpy.types.Object.html?highlight=to_mesh#bpy.types.Object.to_mesh)

### CODE REVIEW

**Comment by ScottishCyclops** [comment]
Hey,

Thanks for your contribution !

I will merge it into a separate 2.8 Branch, because otherwise it would not be compatible with 2.79 anymore.

Have you tested it successful ?

Looking at your changes, your removed "settings="PREVIEW". However, it is important to apply the preview settings (and not the render settings) of the modifiers.
Did you remove it because it is the default behavior in 2.8 ?

Scott

**Comment by hsab** [comment]
Yes that function parameter is removed from the 2.8 API.

I tested successfully in 2.8 but there are some bug related to the internal code
https://github.com/JacquesLucke/animation_nodes/issues/989

**Comment by ScottishCyclops** [comment]
I created a "2.8" Branch. I don't think I can accept your pull request into a branch other than the one you selected.
Could you make another pull request on the new 2.8 Branch ?

Thanks !

Scott

**Comment by ScottishCyclops** [comment]
Closed as I just uploaded a 2.8-complient version to the [2.8 branch](https://github.com/ScottishCyclops/tensionmap/tree/2.8)

**Pull request closed without merging**
